{% set version = "7.6" %}

package:
  name: ferret_datasets
  version: {{ version }}

source:
  fn: ferret_datasets-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/FerretDatasets/archive/v{{ version }}.tar.gz
  sha256: b2fef758ec1817c1c19e6225857ca3a82c727d209ed7fd4697d45c5533bb2c72

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
  run:

test:
  imports:

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'Data for PyFerret examples'

extra:
  recipe-maintainers:
    - eugeneburger
    - josborne-noaa
    - karlmattsmith
    - ocefpaf
