{% set version = "7.1.0" %}

package:
  name: ferret_datasets
  version: {{ version }}

source:
  fn: ferret_datasets-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/FerretDatasets/archive/v{{ version }}.tar.gz
  sha256: 6a498eab8803ff4df9b95ff6dcfe1232822c4d2ab1e93c442bd02be52e335771

build:
  number: 0
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - pyferret
  run:
    - python
    - pyferret

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'Data for pyferret examples.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
