{% set version = "7.4" %}

package:
  name: ferret_datasets
  version: {{ version }}

source:
  fn: ferret_datasets-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/FerretDatasets/archive/v{{ version }}.tar.gz
  sha256: eb82653ee960a3e71e1fb2ae686dbe6570e82ed6878da18ece4435c49eb285e5

build:
  number: 0
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - pyferret
  run:
    - python
    - pyferret

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'Data for pyferret examples.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
