travis:
  secure:
    BINSTAR_TOKEN: aiZ11Kyv9s6UGTSEJKv26cr75CIORIsDSiNdEciNKKxQ2FPBm/t30Ip7T/zk5loR3t+/NlV2TF1vPfJpznrfefBR5WReVgxba35BPMC/6DNMp0KvpwsOgoULGkEtoQwR9/UZpxfz7D3+uhL4IrM96OaPjKwY3OgCsrQRfEK6YlhLbLlVGlvIJOsA/Z/XLQGqu7ECr4RdQUI97EcDNyrpPXXo7Fk8Jn2NfBlae3AskSKms8Kk7V+YAmn8D6Vb7tkLZWC+1xB+Am+Ied90u4oML/dkVyRmgFE/15+J4AfAd1jhc2kX+A2lIH6a+VrUDlPVtFF933NbrFpK9+XmAm2f9J/UxHxjNFLpLLAQX8OnJFgcz8MjboinfzWy2txe9wCjjSV/ddZuOHUqo2Zo0VQ3WogNt27mhZFRw2qzo+PQJS/AqgImPFJZveZgeSbABnmewbVL4JeitthOHrtjiHSnKJzjWxmAiDpfE4VlNU0Qu1h7n+aiKRilEpwzrnkBOA6Tvm5ysojIGhMiYDFSHTd0mQIctRaQ2eVFPI+Dl5tOvSgo7wCPcuNgkiQ2BXq6u9yDooVVBe5lW3Lg+cu+a2zURxzHkB+DzbAHw1fW0ff90c5sgsjocxO+HrjW+TuFE5FRS5YdoLNurRP51fJSvQdxga0U2hTQUwdBPthiB0p2GIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
