travis:
  secure:
    BINSTAR_TOKEN: q4T8LryKP8GcLuHIKdSAQb/Ip97ntvatiY0Y1WvKwOdmjB2Dko19qxLHEHXDQ5eieK6R9TBOmT0lFgD02JcX2FqeXnWjMdnDHHav2+d7Z9qdiTt97dr0pUF7nVgrqW68iSmyg74HVHrpP7NpoWUZBrrPG59P9tvZF9Jm+lVmLRd7UDssKknHZVrR6BBedbOD/sQXRt4qzce/t8ivL+bcZ+gVkF4wmP3+rr5HorhzL6AFcWx0jOSUxmRs7mUABso6mvSYmE4k0QVtwpaAXwqacnIsMPWM0R2/fXPR8lkBHIYWj+2cwsYMb40/Nddz8s4X9QlI9Y18rODB19eneDqf1YfowYPZ3a4xPev229bCcSwC78Env0AiGeG+LXwFdtQfjCIfjzbfPN4CodGlDlnLw/ztOEGLkFoleu3YCvD9sxVZUqrET43a27IuHZ2Ri6e0OpjQs0ASxrIOeJ+SLUVha2iF700D1Ldgu1a/ORTYiqUaYW2td5fd1Pfo2Oxhz8l38nqm8KDZE+jaVrxelsSUoNox8mqX8u55cXje9maDX/PyPrh+8jHvWvgUnulq6X3hbDy2KHnCX5aWqI142VRv/dg1Jd8JndibRa8lmx6OugMKOTtMmLlvxjPHkpEENVyNrbZp1w9tITj+M4563vmisGC4sWCB6fiKECvxcg+4VjU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
